---
title: "Solution : préparation éléments théoriques"
output:
  html_document:
    mathjax: null
    theme: lumen
    css: ../styles2.css
link-citations: true
urlcolor: blue
---
1. Au plus bas niveau, quel est le code qu'un ordinateur comprend réellement ?

*  _le code machine qui peut être exprimé purement en binaire_

2. Quels sont les éléments fondamentaux de tous programmes, peu importe le langage dans lesquels ils sont écrits ?

* _les données (variables et constantes) et les fonctions_

3. Quelle est la différence principale entre une struct et une classe, en C\# ?

* _Une struct va donner des objets type valeur, tandis qu'une classe va donner des objets type référence_

4. Nommez un langage de programmation qui a précédé le C\# et qui avait des `struct`.

* _Le C_

5. Lorsqu'une fonction reçoit un tableau en paramètre, le paramètre représente une copie du tableau envoyé. V ou F ?

* _F. Les tableaux sont des objets basés sur une classe, donc ils sont type référence. Lorsqu'on envoit un tableau à une fonction, on envoit réellement une référence á un tableau_

6. Il est impossible que plusieurs fonctions portent le même nom. V ou F ?

* _F. Il est possible ; c'est la surcharge de fonction_

7. Quelle est la valeur par défaut pour n'importe quelle donnée qui est d'un type défini par une classe ?

* _La valeur par défaut pour une référence est null_

8. En C\#, est-ce que toutes les données sont des objets ?

* _Oui. Les objets peuvent être type valeur ou type référence_

9. Nommez le défaut principal, vu en classe, du paradigme procédural.

* _La validation décentralisée_

10. Qu'est-ce l'instanciation ?

* _L'action de créer un nouvel objet dans la mémoire de l'ordinateur_

11. Qu'est-ce un attribut d'objet ?

* _Une donnée propre à une instance (un objet)_

12. Qu'est-ce une méthode d'objet ?

* _Une action ou un comportement qu'un objet peut réaliser, souvent en traitant la valeur de ses attributs. Une méthode est une fonction_

13. Qu'est-ce qui défini l'état d'un objet ? (pour modifier un objet, il faut modifier ces ...)

* _L'ensemble des valeurs des attributs de l'objet définit son état_

14. Qu'est-ce qu'une référence ?

* _Quelque chose qui réfère à un objet instancié en mémoire. C'est l'adresse où se trouve un tel objet_

15. Pourquoi cacher des éléments d'un objet d'un client ? (pourquoi l'encapsulation ?)

* _Assurer une utilisation contrôler de l'objet qui ne permet pas à un client de mettre l'objet dans un étant incohérent_

16. Qu'est-ce qui forme l'interface publique d'une classe ?

* _L'ensemble de ses membres (données et méthodes) publics. Autrement dit : tout ce qui est public_

17. Une propriété est une façon raccourcie d'écrire une méthode «mutateur» et une méthode «accesseur». V ou F ?

* _V. Les propriétés offrent une syntaxe alternative pour écrire des méthodes Get/Set_

18. Une propriété calculée a un volet `set` où il faut affecter un attribut. V ou F ?

* _F. Une propriété calculée ne contrôle pas un attribut. Ce genre de propriété n'a qu'une partie get, où le résultat d'un traitement est retourné_

19. Il est * *toujours** garanti qu'un client ne peut modifier l'état d'un objet à travers un accesseur public.

* _F. Si un objet α retourne une référence à un objet mutable β qui le compose, le client peut modifier β et indirectement modifier l'état de α. Par exemple, si un objet retourne une référence à un tableau qu'il possède comme attribut..._

20. Quel est le but d'un mutateur ?

* _De faire une mutation à l'état d'un objet en modifiant un seul attribut de l'objet_

21. Il est approprié d'avoir une stratégie de validation dans un mutateur. V ou F ?

* _V. Si le mutateur (set) est public et que l'attribut associé est privé, le client sera forcé à passer à travers la validation écrit dans le mutateur_

22. Dans quel cas est-ce qu'il est sécuritaire de retourner une référence à un attribut d'un objet ?

* _Dans le cas où la reférérence réfère à un objet immuable (comme une string)_

23. Supposons que `s` est une référence vers une `string`. `s.ToLower()` retourne une nouvelle `string`. V ou F ?

* _V. Les string sont immuables_

24. Concaténer des `string` par `+` peut être long pour quelles raisons ? Quelle est la solution ?

* _La création de string temporaire, mais surtout à cause du besoin de copier tous les caractères des deux strings pour en former une nouvelle. La solution est d'utiliser un StringBuilder pour construire des string potentiellement longues_

25. Pourquoi est-ce que c'est déconseillé de retourner un attribut de type tableau ?

* _Les tableaux ne sont pas des objets immuables, alors un client peut faire ce qu'il veut avec le contenu du tableau_

26. Si le `set` d'une propriété qui contrôle un attribut de type tableau est public, le client peut modifier le contenu du tableau. V ou F ?

* _F. Il peut modifier le CONTENEUR_

27. Pourquoi est-ce que c'est long insérer un élément au début d'un tableau ?

* _Il faut décaller tous les éléments du tableau d'une position !_

**Nouvelles questions**

28. Pourquoi est-ce que c'est long retirer un élément au début d'un tableau ?

* _Il faut décaller tous les éléments du tableau d'une position !_

29. Quelle est la différence significative entre un tableau « classique » et un tableau dynamique ?

* _ Un tableau dynamique peut changer sa capacité pendant l'exécution du programme_

30. Décrivez les étapes necéssaires pour redimensionner un tableau dynamique.

* _Calculer la nouvelle capacité; Créer un nouveau tableau avec la capacité calculée; Copier les éléments du tableau actuel dans le nouveau tableau; Faire pointer la référence aux éléments vers le nouveau tableau_

31. Lorsqu'un élément type référence est ajouté à une `List<T>` par la méthode `Add(...)`, la liste va réellement contenir une **copie** de la référence ajoutée. V ou F ?

* _V. La méthode `Add(...)` prend un paramètre par copie (pas de mot clé `ref`), donc la méthode va utiliser une copie de la référence envoyée_

32. Supposons un élément `e` de type référence qui est ajouté dans une `List<T> éléments` initialement vide. L'état de `e` est ensuite changé d'une manière quelconque. Est-ce que l'objet modifier est le même que celui retourné par `éléments[0]` ? Autrement dit, est-ce que modifier `éléments[0]` modifie aussi `e` ? Expliquez.

* _Oui, car `e` et `éléments[0]` sont des références qui pointe au **même** objet en mémoire_

33. En C\#, le mot clé `using` sert seulement à importer des bibliothèques (System.IO, LibJeux, etc.). V ou F ?

* _F. Il est aussi utiliser pour créer des blocs `using (...){...}`. Un bloc using est souvent utilisé pour créer une section de code _utilisant_ un `StreamReader`, par exemple_

34. Qu'est-ce qui arrive si un `StreamReader` ayant ouvert un fichier n'est pas fermé ?

* _Aucun autre programme pourra modifier le fichier, car le fichier reste occupé_

35. Expliquez une façon possible de savoir si tout le contenu d'un fichier a été lu par un `StreamReader`.

* _Lorsque la méthode `ReadLine()` de l'objet `StreamReader` retourne `null`_
