---
title: "202"
output:
  html_document:
    mathjax: null
    theme: lumen
    css: styles.css
link-citations: true
urlcolor: blue
---

----

**Checklist fin de session**

1. [Regardez le solutionnaire pour l'exercice sur les interface](ex/SolExInterface.zip);
2. [Exercices de préparation pour l'examen](ex/formatifExamF.html)
3. Collection **A** d'exercices sur délégués et lambdas (à venir...);
4. Collection **B** d'exercices sur délégués et lamdas (à venir...);
5. Questions théoriques pour l'examen (à venir...);
6. PFI !

----

## Planification 
9. Mardi 21 mai : Exercices divers, cours de révision;
10. **Jeudi 30 mai : Examen final;**
11. Samedi 2 juin : Remise de la PFI avant minuit;
12. Mardi 6 juin : Accès à vos notes finales sur ColNet.
 
----

## Chapitres
1. [Introduction aux paradigmes](ch1/chapitre1.html)
2. [`struct`](ch2/chapitre2.html)
3. [Les objets](ch4/chapitre4.html)
4. [De procédurale à orientée objet](ch3/chapitre3.html)
5. [`class`](ch5/chapitre5.html)
6. [Encapsulation](ch6/chapitre6.html)
7. [Constructeur paramétrique](ch7/chapitre7.html)
8. [Propriétés](ch8/chapitre8.html)
9. [`string`, objet immuable et `StringBuilder`](ch9/chapitre9.html)
10. Distinctions entre conteneur et contenu (notes prises en classe)
11. Propriété indexée (notes prises en classe)
12. [Tableau dynamique](ch11/chapitre11.html)
13. [`List`](List.pdf)
14. [`StreamReader`](Fichier.pdf)
15. [`StreamWriter`](ch12/chapitre12.html)
16. [La pile](ch13/chapitre13.html)
17. [L'héritage et le polymorphisme](ch15/chapitre15.html)
18. [Les classes abstraites](ch16/chapitre16.html)
19. [Interfaces](ch17/chapitre17.html)
20. [Cycle de vie](ch18/chapitre18.html)
21. [Copiage et clonage](ch19/chapitre19.html)
22. [Délégués et lambdas](ch20/chapitre20.html)

## Exercices
* [Fonction et Random](rev/exercices.html)
* [Tableaux 1D](rev/exercices2.html)
* [Une première `struct`](ch2/exercices.html)
* [Entier naturel](ex/1.html)
* [Éléments théoriques (examen intra)](rev/prepex1.html)
	* [Solutions](rev/prepex1S.html) 
* [Carte de jeux](ex/2.html)
	* [Solution](Exercice_CarteDeJeu.zip)
* [Équilibre de parenthèses](ex/3.html)
	* [Solution](ex/SolutionParenthèses.zip)
* [Interfaces](ex/4.html)
	* [Solution](ex/SolExInterface.zi)

## Laboratoires
1. [Tortue](lab/1.html)
	* [FAQ](lab/1f.html)
	* [Problèmes populaires](lab/1r.html)
2. [Base de jeux](lab/2.html)
3. [ColNet.tv](lab/3.html)
4. [Jeu 2D](lab/4.html)
5. [PFI](pfi/pfi.html)
