---
title: "Activité préparatoire 4"
output:
  html_document:
    theme: lumen
    css: styles.css
link-citations: true
urlcolor: blue
---

_Strutures de données et programmation orientée objet_  
_429-202-RE_

## Consignes générales
Lisez attentivement les notes du chapitre 4 sur le site [profd.info](http://profd.info/ped891/travail2/notes.html).

Visionnez ensuite les capsules sur le site. Pendant le visionnement, les capsules s'arrêreteront à des moments clés. Vous serez mené de répondre à des questions à propos du contenu, afin de reprendre la capsule.

Après le visionnement des capsules, complétez l'exercice préparatoire. Votre travail sera obligatoirement montré à vos camarades de classe, ainsi à votre enseignant, dans les activités qui auront lieu au prochain cours. De plus, votre travail servira de projet de départ pour le prochain exercice en classe.

La théorie présentée ne sera pas réexpliqué en classe. Donc, la maîtrise du contenu présenté dans les capsules est nécessaire pour la compréhension et la réussite des activités du prochain cours.

## Consignes particulières
Il y a deux capsules de 5 minutes chacune. La première capsule présente comment écrire une classe en C\# avec tous les ingrédients de base (attributs, méthodes, constructeur). La deuxième capsule est à propos de tester la classe en profondeur et d'identifer, par la suite, les limites de celle-ci avec l'implémentation employée. La solution à ces limites sera vu au prochain cours. Chaque capsule contient des courtes phases d'exercices où vous devriez rédigez du code. Celles-ci doivent être réalisée afin de poursuivre la vidéo.

Pour l'exercice préparatoire, vous devriez créer une nouvelle classe, dont la classe _Chat_, qui représente un chat. Vous devriez concevoir les caractéristiques et comportements d'un chat, implémentez la classe et ensuite la testez. Consultez le [guide d'accompagnement](exercicePrep.html#guide), pour des pistes de travail.

## Objectif d'apprentissage

* Définir qu'est-ce un attribut, une méthode et un constructeur;
* Écrire une classe contenant des attributs, méthodes et un constructeur;
* Tester sa propre classe;
* Identifier les limites/problèmes potentiels de la classe.

