---
title: "Chapitre 4"
output:
  html_document:
    mathjax: null
    theme: lumen
    css: styles.css
link-citations: true
urlcolor: blue
---

## Introduction
Le chapitre 4 présente les ingrédients pour écrire ses propres classes. Les activités préparatoires amènent à l'élaboration de petites classes, ainsi qu'à la réalisation d'un enjeu par rapport à ces classes et à la programmation orientée objet en générale.

Pendant les heures de cours, un nouveau principe sera acquis afin de créer des classes idiomatiques qui n'ont pas les faiblesses identifiées.

Lisez les [**consignes**](consignes.html) à propos du travail à faire à la maison.

----

## Activités préparatoires

1. [Notes : définition des éléments de bases d'un objet](notes.html);
2. [Capsule #1 : écrire sa première classe](../classeInv/capsule1.html);
3. [Capsule #2 : tester sa première classe et le problème de validation](../classeInv/capsule2.html);
4. [Mini exercice : écrire une classe `Chat`](exercice.html).

## Activités en classe

1. Présentation : principe d'encapsulation;
2. Exercice : implémenter l'encapsulation dans la classe `Chat`.
