---
title: "Jeu 2D"		
output:
  html_document:
    mathjax: null
    theme: lumen
    css: ../styles.css
link-citations: true
urlcolor: blue
---
**ATTENTION**
Il y a avait un problème dans `Scène.cs`. Remplacer le code avec le suivant :
```
using System;
using System.Collections.Generic;
using System.Windows.Forms;
using SFML.Graphics;
using SFML.System;

//Cette classe est déjà complétée
namespace Labo4_Jeu
{
    public class Scène
    {
        private List<Ennemi> ennemis;
        private Joueur joueurPrincipal;
        private Carte carteActuelle;
        private Text[] hud;

        public Carte CarteActuelle
        {
            get { return carteActuelle; }
            set { carteActuelle = value; }
        }

        public Joueur JoueurPrincipal
        {
            get { return joueurPrincipal; }
            set { joueurPrincipal = value; }
        }

        private List<Ennemi> Ennemis
        {
            get { return ennemis; }
            set { ennemis = value; }
        }

        private Text[] HUD
        {
            get { return hud; }
            set { hud = value; }
        }

        public void MettreÀJour(RenderWindow fenêtre)
        {
            MettreEnnemisÀJour();
            JoueurPrincipal.MettreÀJour();
            
            VérifierCollision();

            MettreHUDÀJour();
            DessinerScène(fenêtre);
        }

        void MettreEnnemisÀJour()
        {
            foreach (var ennemi in Ennemis)
                ennemi.MettreÀJour();
        }

        void MettreHUDÀJour(RenderWindow fenêtre)
        {
            HUD[0].DisplayedString = $"Joueur\n\n{JoueurPrincipal}";
            for (int i = 0; i < Ennemis.Count; i++)
            {
                Ennemi e = Ennemis[i];
                HUD[i + 1].DisplayedString = $"Ennemi\n\n{e}";
            }
        }

        void VérifierCollision()
        {
            foreach (var ennemi in Ennemis)
            {
                if (ennemi.Position == JoueurPrincipal.Position)
                {
                    ennemi.Attaquer(JoueurPrincipal);
                    if (JoueurPrincipal.PV <= 0)
                        Application.Exit();
                }
            }
        }

        void DessinerScène(RenderWindow fenêtre)
        {
            fenêtre.Clear(Color.Black);
            fenêtre.Draw(CarteActuelle);
            
            fenêtre.Draw(JoueurPrincipal);
  			
            foreach (var ennemi in Ennemis)
            	fenêtre.Draw(ennemi);

            foreach (var e in HUD)
                fenêtre.Draw(e);
            fenêtre.Display();
        }

        public Scène()
        {
            Ennemis = new List<Ennemi>(1);
        }

        public void AjouterEnnemi(Ennemi ennemiÀAjouter)
        {
            Ennemis.Add(ennemiÀAjouter);
        }

        public void CréerHUD()
        {
            HUD = new Text[Ennemis.Count + 1];

            Text textJoueur = new Text();
            textJoueur.FillColor = Color.White;
            textJoueur.CharacterSize = 20;
            textJoueur.Font = new Font("../../04B_30__.TTF");
            textJoueur.Position = new Vector2f(700, 50);

            hud[0] = textJoueur;
            
            for (int i = 1; i < Ennemis.Count + 1; i++)
            {
                Text text = new Text();  
                text.FillColor = Color.White;
                text.CharacterSize = 20;
                text.Font = new Font("../../04B_30__.TTF");
                text.Position = new Vector2f(700, 150 * i + 30);
                hud[i] = text;
            }
        }
    }
}
```

## Consignes

* Récupérer le projet de départ [ici](Labo4_Jeu - Départ.zip);
* Compléter les classes marquées;
* Pour alléger le travail, **aucune** validation est nécessaire dans ce laboratoire.

## Mise en contexte
Vous travaillez sur un jeu 2D à l'aide de la bibliothèque _SFML.NET_. Il existe déjà une base, mais vous devez compléter les classes pour les entités du jeu, soit le joueur et les divers types d'ennemis.

## Le gestionnaire de ressources
La classe `GestionnaireRessources` est une classe `static` (une classe qui ne sert pas de plan pour créer des instances, mais plutôt que de « conteneur » pour des données et méthodes utiles, comme la classe `Math`). Cette classe contient des ressources chargées dans la mémoire du programme, comme des textures.

Dans cette classe, il existe la propriété `Textures` qui est un tableau de textures. Pour accéder à cette propriété, il faut utiliser la syntaxe `GestionnaireRessources.Textures[...]`. La syntaxe _nomDeLaClasse.Membre_ est pour les membres (attributs, propriété, méthodes) `static`.

Ce tableau contient déjà des textures chargées. Voici son contenu par position :

0. texture du joueur;
1. texture d'un guerrier;
2. texture d'un patineur.

## Les entités
Une entité est quelque chose de « vivant » dans le jeu. Par exemple, le joueur et les ennemis sont des entités. La classe entité en soi **n'est pas instanciable**, car elle sert que de base pour des classes dérivées.

Les entités se déplacent par des unités discrètes, pour donner l'impression de se déplacer par cases dans une grille.

### Attributs/Propriétés

* un `Vector2i position` qui représente la position de l'entité. `Vector2i` est une classe accessible grâce au `using SFML.System` et représente un vecteur 2D où les composantes sont des entiers;
* un `Sprite spriteÀDessiner` qui représente essentiellement l'image à afficher pour visualiser une entité;
* un `int pV` qui représente les points de vie de l'entité;
* un `int déf` qui représente les points de défense de l'entité;
* un `int atq` qui représente les points d'attaque de l'entité;
* une `List<uint> tuileBloquées` qui représente une liste de type de tuiles dont l'entité ne peut pas se déplacer dessus. Un `uint` est un nombre naturel (entier positif).

Tous les types références qui ne sont pas immuables doivent être `private` pour le `get` et le `set`. Une `Sprite` est une `class`. Un `Vector2i` est une `struct`.

### Méthodes

* `AjouterTuilesBloquée(...)` : cette méthode doit prendre en paramètre un `uint` qui représente une type de tuile inaccessible à l'entité. Ce type est ajouté dans la liste, si elle n'est pas déja présente dans la liste. Cette méthode doit être accessible dans les classes enfants, mais pas à d'autres codes clients.
* `Déplacer(...)` : cette méthode doit prendre en paramètre un `Vector2i` qui représente le _delta_ de position à faire. Par exemple, le delta pourrait être de (1,0), ce qui déplacera l'entité à droite d'une unité. En plus de tenter de changer la position de l'entité, cette méthode doit retourner un `bool` indiquant si le déplacement est réussit ou non. Il est possible que déplacer une entité soit impossible si :
	* la nouvelle position est hors borne (Utilisez `Program.ScèneActuelle.CarteActuelle.NbColonnes/NbLignes`);
	* la nouvelle position tombe sur une tuile bloquée (Utilisez `Program.ScèneActuelle.CarteActuelle[y,x]`).
Cette méthode doit être accessible dans les classes enfants, mais pas à d'autres codes clients.
* `MettreÀJour()` : cette méthode sera appelée à chaque mise à jour de la scène (l'univers du jeu). C'est ici que la logique principale des entités se fait. Par exemple, pour le joueur, l'état des touches pressées est vérifié et le joueur se déplace en accord. Pour un ennemi, il est déplacé dans sa direction de patrouille. Cette méthode doit être `public`. Le jeu est conçu pour faire 60 mise à jour par seconde.
* `SubirDégats` : cette méthode doit prendre en paramètre un `int` qui représente des dégâts à infliger sur l'entité. Par défaut, une entité perd un nombre de point de vie équivalent aux dégâts à infliger moins sa défense. Par contre, un entité doit toujours subir au moins un dégat. Cette méthode doit être `public`.
* `ToString()` : cette méthode doit retourner une chaine formattée de la façon suivante :
```
PV:0
ATK:0
DEF:0
```
où les `0` sont les valeurs respectives de PV, ATK et DEF de l'entité.

### Constructeur
La classe possède un constructeur paramétrique qui prend en paramètre une `Texture` et un `Vector2i`. Il est possible d'initialiser le `spriteÀDessiner` avec un `new Sprite` en utilisant le constructeur paramètrique de `Sprite` qui prend en paramètre une `Texture`.

## Le joueur
La majorité de la classe `Joueur` est déjà écrite. Complétez aux endroits indiqués.
Un joueur a 15 PV, 5 d'ATK et 3 DEF.

## Les ennemis
Il existe deux sortes d'ennemis concrêtes : les guerriers et les patineurs

Tous les ennemis, peu importe la spécialisation, ont les suivants :

* un comportement de patrouillage — les ennemis se déplacent dans une direction choisie au hazard tant qu'ils ne peuvent continuer. S'il est impossible de se déplacer, leur direction de patrouillage est inversée.
* Un constructeur paramétrique qui prend en paramètre une `Texture` et un `Vector2i`. La texture est celle qui sera appliquée au `Sprite` de l'ennemi et le vecteur représente la position initiale de l'ennemi.
* un attribut `Vector2i directionPatrouille` qui indique la direction que l'ennemi se déplace lors de son patrouillage. Cette direction doit être initialisé dans le constructeur. La direction est choisie au hazard parmi les 8 points cardinaux possibles **et** la direction $0$ (vecteur de (0,0)). Utilisez le `Random` `GestionnaireRessources.RNG` pour générer des nombres aléatoires;
* une méthode `MettreÀJour()` qui déplace l'ennemi à chaque 60 appels de mise à jour (à chaque 60 frames). Créez un compteur pour cette tâche;
* une méthode `Attaquer(...)` qui prend en paramètre une `Entité` cible pour recevoir l'attaque. La cible doit donc subir des dégats;
* 10 PV et 2 DEF.

### Les guerriers
Les guerriers sont tellement _hot_ qu'ils peuvent se déplacer sur de la lave.

Ils ont 6 d'ATK.
En plus, ils ont une caractéristique de plus que les autres ennemis : ils ont de l'armure.

Tous les guerriers ont des points d'armure (`int`). Le nombre de points est déterminé à l'instanciation d'un guerrier et doit être un nombre aléatoire entre 1 et 3 inclusivement. Lorsqu'un guerrier subit une attaque, son armure absorbe des dégâts. Un point d'armure → un dégât reçu de moins.
Les guerriers ont 2 points d'armure.

**N.B. : ** Ceci ne sera pas tester _in game_, car le joueur ne peut pas attaquer les ennemis dans cette version du jeu. Vous devez tout de même implanter ce comportement. Vous pouvez faire des tests personnalisés dans la console.

Finalement, le `ToString()` des guerriers doit retourner une chaine formatée comme suit :
```
PV:0
ATK:0
DEF:0
ARM:0
```
où ARM est pour les points d'armures.

### Les patineurs
Les patineurs sont tellement _cool_ qu'ils peuvent **seulement** se déplacer sur de la glace.
Ils ont 3 d'ATK.

## Bonus
Soyez créatif et soyez récompensé avec des points bonis. Vous pouvez, par exemple :

* Changer la carte;
* Changer les graphiques;
* Ajouter un nouveau type d'ennemi;
* Ajouter de nouvelles cartes et un mécanisme pour naviguer entre elle;
* etc.

## Remise
Le projet complet doit être soumis avant minuit pour le mardi 7 mai. Assurez-vous de nommer le .zip avec les noms des participants. La version « papier » doit être remise le 14 mai, en classe.
